version: "3.3"
services:
  eksperiment:
    platform: "linux/x86_64"
    image: jnkql/mas
    volumes:
      - ./data/fasttext:/app/data/fasttext
      - ./models:/app/models 
    command: python3 /app/fasttextmf.py run