version: "3.3"
services:
  eksperiment:
    build: .
    volumes:
      - ./data/fasttext:/app/data/fasttext
      - ./models:/app/models 
    # command: sleep 2000
    command: python3 /app/fasttextmf.py run